language: ruby
cache: bundler
sudo: false

rvm:
  - '2.1'
  - '2.2'

cache:
  directories:
    - "travis_phantomjs"

before_install:
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"

addons:
  postgresql: '9.5'

before_script:
  - psql -c 'create database coupons_test;' -U postgres
  - mysql -e 'create database coupons_test;' -u root

env:
  - 'DATABASE_URL=postgres://postgres@localhost/coupons_test'
  - 'DATABASE_URL=mysql2://root@localhost/coupons_test'

gemfile:
  - Gemfile
  - gemfiles/rails_4_2.gemfile

addons:
  code_climate:
    repo_token:
      secure: 'iD2QMCQ9RHeaThxeRxkPeTMgLjOZhTXaaBnhFUMMe2CTbmqfWSld/+GPOYECr9VEEjPOyN8lkfTJ1benxa0Wog6xk7DC7aCXjgftpA95OmsJd+9czGv/2pp0D4m6xWGkKgB9IYM3IVhzLqqGeAjxInKgQOjVhKgkaaRYGUYTrFc='
